version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener

  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgres://postgres:password@db:5432/url_shortener
    command: bash -c "bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"

volumes:
  pg_data:
