default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: url_shortener_test

production:
  primary: &primary_production
    <<: *default
    database: url_shortener
    username: postgres
    password: password
    host: db 
    port: 5432
  cache:
    <<: *primary_production
    database: url_shortener_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: url_shortener_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: url_shortener_production_cable
    migrations_paths: db/cable_migrate
